name: NT3_PUB

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: 🛎 Check out main
        uses: actions/checkout@master
        with:
          lfs: 'true'
          repository: ${{ secrets.NT3_MAIN_BIN_PATH }}
          token: ${{ secrets.NT3_REPO_TOKEN }}
          fetch-depth: 1
      - name: make dir set bin
        run: |
          mkdir NT3_REPO
          7z  x -p${{ secrets.NT3_ZIP_PASS }} bin.7z
          ren NT3_MAIN_TEMP NT3_MAIN
      - name: debug dir
        run: |
          cd NT3_MAIN
          ls
      - name: HGP
        run: |
          cd NT3_MAIN
          java -Xms128m -Xmx4g -jar NT3_001_Main.jar HugoGitPull
      - name: TN
        run: |
          cd NT3_MAIN
          java -Xms128m -Xmx4g -jar NT3_001_Main.jar TistoryNoti
      - name: WC
        run: |
          cd HCM
          java -Xms128m -Xmx4g -jar NT3_001_Main.jar HugoContentMake
      - name: HGPA
        run: |
          cd NT3_MAIN
          java -Xms128m -Xmx4g -jar NT3_001_Main.jar HugoGitPushAll
